---
#
# This playbook unset hot add values to VM
#
- name: Unset hot add values to VM
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: vcenter_ip
      prompt: vCenter IP or hostname
      private: no

    - name: vcenter_username
      prompt: vCenter username
      private: no

    - name: vcenter_password
      prompt: vCenter password
      private: yes

    - name: datacenter
      prompt: VMWare datacenter
      private: no

    - name: vm_name
      prompt: VM Name
      private: no

  tasks:
  - name: "Get VM info"
    community.vmware.vmware_guest_info:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      name: "{{ vm_name }}"
    register: vm_info
    delegate_to: localhost
    connection: local

  - block:
      - name: "Ends play if VM is not powered off"
        debug:
          msg: "This play must be applied when VM is powered off"

      - name: "End play"
        meta: end_play
    when: vm_info.instance.hw_power_status != "poweredOff"

  - name: "Unset hot add values to VM"
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      uuid: "{{ vm_info.instance.hw_product_uuid }}"
      hardware:
        hotadd_cpu: false
        hotadd_memory: false
    delegate_to: "localhost"
    connection: local

